// Bundles the pure-logic game modules in games/*.mjs into the single-file
// PWA index.html. Each module's exports are wrapped in a namespaced IIFE
// (e.g. TICTACTOE.bestMove) so the same files are import-able by node:test
// AND inlined for the browser. Run: `npm run build`.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const gamesDir = join(root, 'games');
const files = readdirSync(gamesDir).filter((f) => f.endsWith('.mjs')).sort();

let bundle = '// Auto-generated by build.mjs — edit games/*.mjs then `npm run build`.\n';
for (const f of files) {
  const id = f.replace(/\.mjs$/, '');
  const ns = id.replace(/[^a-z0-9]/gi, '').toUpperCase();
  const src = readFileSync(join(gamesDir, f), 'utf8');
  const names = [
    ...src.matchAll(/export\s+(?:function|const|let|var|class)\s+([A-Za-z0-9_$]+)/g),
  ].map((m) => m[1]);
  if (!names.length) throw new Error(`No exports found in games/${f}`);
  const body = src.replace(/^\s*export\s+/gm, '');
  bundle += `const ${ns} = (function(){\n${body}\nreturn { ${names.join(', ')} };\n})();\n`;
}

const tpl = readFileSync(join(root, 'index.template.html'), 'utf8');
if (!tpl.includes('/*__GAMES__*/')) {
  throw new Error('index.template.html is missing the /*__GAMES__*/ marker');
}
writeFileSync(join(root, 'index.html'), tpl.replace('/*__GAMES__*/', () => bundle));
console.log(
  `Built index.html · ${files.length} game module(s): ` +
  files.map((f) => f.replace(/\.mjs$/, '')).join(', '),
);
